window.runHistoryChecks = async check => {
  const settle = async () => {
    await new Promise(resolve => setTimeout(resolve, 20));
    while(document.body.inert) await new Promise(resolve => setTimeout(resolve, 10));
  };
  switchPiece('jcard');
  projectHistory.reset();
  selectedLayerId = 'text-test';
  const before = {...selectedLayer()};
  deleteSelectedLayer();
  await settle();
  check(!currentState().layers.some(layer => layer.id === before.id) && !document.getElementById('btnUndo').disabled,
    'deletion enables Undo and archives the item');
  await undo();
  check(currentState().layers.some(layer => layer.id === before.id && layer.font === before.font), 'Undo restores deleted text formatting');
  await redo();
  check(!currentState().layers.some(layer => layer.id === before.id), 'Redo repeats deletion');
  const archived = deletedProjectItems().find(item => item.entry.layer?.id === before.id);
  restoreDeletedItems([archived]);
  await settle();
  check(currentState().layers.some(layer => layer.id === before.id && layer.x === before.x), 'Deleted items restores original placement');
  await undo();
  check(!currentState().layers.some(layer => layer.id === before.id), 'recovery itself is undoable');
  await redo();
  projectHistory.reset();
  selectedLayerId = before.id;
  pushHistory(); selectedLayer().size = 8; render(); await settle();
  pushHistory(); selectedLayer().size = 10; render(); await settle();
  await undo(); check(currentState().layers.find(layer => layer.id === before.id).size === 8, 'multi-step Undo restores preceding edit');
  await undo(); check(currentState().layers.find(layer => layer.id === before.id).size === before.size, 'second Undo restores original value');
  await redo(); check(currentState().layers.find(layer => layer.id === before.id).size === 8, 'Redo traverses edit history');
  selectedLayerId = before.id;
  pushHistory(); selectedLayer().size = 9; render(); await settle();
  check(document.getElementById('btnRedo').disabled, 'new edit clears the redo branch');
  const ctrlZ = new KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true});
  document.body.dispatchEvent(ctrlZ); await settle();
  check(ctrlZ.defaultPrevented && currentState().layers.find(layer => layer.id === before.id).size === 8, 'Ctrl+Z undoes canvas edits');
  document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Z',ctrlKey:true,shiftKey:true,bubbles:true,cancelable:true})); await settle();
  check(currentState().layers.find(layer => layer.id === before.id).size === 9, 'Ctrl+Shift+Z redoes edits');
  await undo();
  document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'y',ctrlKey:true,bubbles:true,cancelable:true})); await settle();
  check(currentState().layers.find(layer => layer.id === before.id).size === 9, 'Ctrl+Y redoes edits');
  const input = document.getElementById('albumNameInput');
  const nativeUndo = new KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true});
  input.dispatchEvent(nativeUndo);
  check(!nativeUndo.defaultPrevented, 'text fields keep native Undo shortcuts');
  switchPiece('label-a');
  restoreMissingGeneratedText();
  projectHistory.reset();
  const label = currentState().layers.find(layer => layer.role === 'labelAlbum');
  selectedLayerId = label.id; deleteSelectedLayer(); await settle();
  switchPiece('jcard');
  await undo();
  check(currentPieceId === 'label-a' && currentState().layers.some(layer => layer.id === label.id), 'Undo returns to edited piece');
  await redo();
  restoreMissingGeneratedText();
  check(currentState().layers.some(layer => layer.role === 'labelAlbum'), 'missing-label recovery works on cassette labels');
  switchPiece('jcard-back'); renderTracksUI(); projectHistory.reset();
  const oldTrack = {...tracksA[0]};
  const trackLayer = currentState().layers.find(layer => layer.trackId === oldTrack.id);
  trackLayer.size = 7.3;
  document.querySelector('#tracksA .track-remove-btn').click(); await settle();
  check(!tracksA.some(track => track.id === oldTrack.id), 'source track deletion captured');
  await undo();
  check(tracksA.some(track => track.id === oldTrack.id) && currentState().layers.find(layer => layer.trackId === oldTrack.id).size === 7.3,
    'Undo restores source track and canvas formatting together');
  await redo();
  restoreDeletedItems(deletedProjectItems().filter(item => item.kind === 'track')); await settle();
  check(tracksA.some(track => track.id === oldTrack.id) && currentState().layers.find(layer => layer.trackId === oldTrack.id).size === 7.3,
    'Deleted items restores source tracks with formatting');
  selectTrackSide('A');
  const ids = selectedTrackLayers().map(layer => layer.id);
  deleteSelectedLayer(); await settle();
  check(ids.every(id => !currentState().layers.some(layer => layer.id === id)), 'whole-list deletion archives every selected layer');
  const file = await projectFiles.encode(getProjectSnapshot());
  const snapshot = await projectFiles.decode(file);
  check(snapshot.state['jcard-back'].deletedLayers.length >= ids.length, 'deleted items travel with saved projects');
  restoreDeletedItems(deletedProjectItems());
  syncTracksToCanvas();
  check(ids.every(id => currentState().layers.some(layer => layer.id === id)), 'restored generated tracks survive subsequent refresh');
  check(document.getElementById('btnLayout').nextElementSibling.id === 'btnColorControls', 'Layout is beside Color');
};
