window.runTypographyChecks = async check => {
  check(!document.querySelector('#typographyCard input[type=range]'), 'typography has no sliders');
  switchPiece('jcard');
  const layer = {id:'type-panel-test',type:'text',text:'Preview this mixtape',font:'sans',size:3,fontWeight:400,letterSpacing:0,lineHeight:1.25,color:'#000000',x:50,y:50,align:'center'};
  currentState().layers.push(layer); selectedLayerId = layer.id; syncFontPanelToLayer(layer);
  projectHistory.reset();
  document.querySelector('[data-type-preset="title"]').click();
  check(layer.size === 5.4 && layer.fontWeight === 800 && layer.lineHeight === 1.12 && layer.font === 'sans', 'visual preset applies without changing font family');
  check(document.getElementById('fontLivePreview').textContent === layer.text && document.querySelector('[data-type-preset="title"]').getAttribute('aria-pressed') === 'true', 'live preview and preset state follow selection');
  await undo();
  check(selectedLayer().size === 3, 'preset change is undoable');
  document.getElementById('btnFontLarger').click();
  check(selectedLayer().size > 3 && selectedLayer().fontWeight === 400, 'larger button changes only size');
  const precise = document.getElementById('fontSizeSlider');
  const beforeEmpty = selectedLayer().size;
  precise.value = ''; precise.dispatchEvent(new Event('change',{bubbles:true}));
  check(selectedLayer().size === beforeEmpty && Number.isFinite(selectedLayer().size), 'empty precise field keeps valid text size');
  precise.value = '100'; precise.dispatchEvent(new Event('change',{bubbles:true}));
  check(selectedLayer().size === 30 && document.getElementById('btnFontLarger').disabled, 'precise size clamps safely');
  const search = document.getElementById('fontSearch'); search.value = 'JetBrains'; search.dispatchEvent(new Event('input',{bubbles:true}));
  check(Array.from(document.getElementById('fontSelect').options).filter(option => !option.hidden).every(option => option.textContent.includes('JetBrains')), 'font search filters families');
  document.getElementById('btnClearFontSearch').click();
  check(Array.from(document.getElementById('fontSelect').options).every(option => !option.hidden), 'clearing font search restores family list');
  selectTrackSide('A');
  const group = selectedTrackLayers();
  const sizes = group.map(item => item.size);
  document.querySelector('[data-type-spacing="1"]').click();
  check(group.every((item,index) => item.letterSpacing === 1 && item.size === sizes[index]), 'spacing changes preserve mixed group sizes');
  document.getElementById('btnAlignRight').click();
  check(group.every(item => item.align === 'right'), 'alignment applies to whole selected track list');
  const color = document.getElementById('fontColorPicker'); color.value = '#aabbcc'; color.dispatchEvent(new Event('input',{bubbles:true}));
  check(group.every(item => item.color === '#aabbcc'), 'color applies to whole selected track list');
  selectedLayerId = null; selectedTrackGroup = null; clearFontPanel();
  document.querySelector('[data-type-preset="caption"]').click();
  check(defaultFontSettings.size === 2 && document.getElementById('fontEditingTarget').textContent === 'Style for new text', 'no-selection controls edit new-text style');
  addNewTextLayer(); closeInlineEdit();
  check(selectedLayer().size === 2 && selectedLayer().fontWeight === 400, 'new text uses the chosen preset');
  document.getElementById('typographyCard').scrollIntoView({block:'start'});
  const panel = document.getElementById('typographyCard');
  check(panel.scrollWidth <= panel.clientWidth + 1, 'typography panel has no horizontal overflow');
  panel.style.width = '260px'; panel.style.boxSizing = 'border-box';
  check(panel.scrollWidth <= panel.clientWidth + 1, 'typography controls fit a narrow sidebar');
  panel.style.width = ''; panel.style.boxSizing = '';
};
